In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt:

In [ ]:
#SPOTIFY GLOBAL MUSIC DATASET
#importing libraries & Loading Dataset
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/spotify_data clean.csv")

print("✅ Dataset loaded successfully!")
display(df.head())
print("\nDataset Shape:", df.shape)
print("\nColumn Names:", df.columns.tolist())
print("\nDataset Info:")
df.info()

✅ Dataset loaded successfully!

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39

Dataset Shape: (8582, 15)

Column Names: ['track_id', 'track_name', 'track_number', 'track_popularity', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type', 'track_duration_min']

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   object
 1   track_name          8582 non-null   object
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   object
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   object
 9   album_id            8582 non-null   object
 10  album_name          8582 non-null   object
 11  album_release_date  8582 non-null   object
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   object
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), float64(1), int64(5), object(8)
memory usage: 947.2+ KB

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
!pip install altair vega_datasets
import altair as alt
import plotly.graph_objects as go

Requirement already satisfied: altair in /usr/local/lib/python3.12/dist-packages (5.5.0)
Requirement already satisfied: vega_datasets in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair) (2.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from altair) (25.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from altair) (4.15.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from vega_datasets) (2.2.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair) (0.28.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair) (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->vega_datasets) (1.17.0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   object
 1   track_name          8582 non-null   object
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   object
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   object
 9   album_id            8582 non-null   object
 10  album_name          8582 non-null   object
 11  album_release_date  8582 non-null   object
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   object
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), float64(1), int64(5), object(8)
memory usage: 947.2+ KB

In [ ]:
df.head()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39

In [ ]:
import pandas as pd
import numpy as np



# ============================================================
# 1) HANDLE DATE COLUMN: album_release_date → datetime
# ============================================================
if 'album_release_date' in df.columns:
    df['album_release_date'] = pd.to_datetime(df['album_release_date'], errors='coerce')
    # Fill missing with earliest valid date
    df['album_release_date'] = df['album_release_date'].fillna(df['album_release_date'].min())


# ============================================================
# 2) NUMERIC COLUMNS: convert → fill median
# ============================================================
numeric_cols = [
    'track_popularity', 'artist_popularity',
    'artist_followers', 'track_duration_min',
    'album_total_tracks'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())


# ============================================================
# 3) CATEGORICAL COLUMNS: fill missing with mode
# ============================================================
categorical_cols = [
    'track_name', 'artist_name',
    'album_name', 'artist_genres',
    'album_type'
]

for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mode()[0])


# ============================================================
# 4) PROCESS GENRE COLUMN: multi-genre → list
# ============================================================
if 'artist_genres' in df.columns:
    df['artist_genres'] = df['artist_genres'].replace('', 'Unknown')
    df['artist_genres_list'] = df['artist_genres'].astype(str).str.split(r'[;,]\s*', regex=True)
else:
    df['artist_genres_list'] = [['Unknown']] * len(df)


# ============================================================
# 5) CREATE YEAR COLUMN
# ============================================================
if 'album_release_date' in df.columns:
    df['Year'] = df['album_release_date'].dt.year
else:
    df['Year'] = np.nan


# ============================================================
# 6) FILL TRACK ID IF MISSING (rare)
# ============================================================
if 'track_id' in df.columns:
    df['track_id'] = df['track_id'].fillna('unknown_track')


# ============================================================
# SUMMARY
# ============================================================
print("Preprocessing complete.")
print("Shape:", df.shape)
print("Columns:", df.columns.to_list())

Preprocessing complete.
Shape: (8582, 17)
Columns: ['track_id', 'track_name', 'track_number', 'track_popularity', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type', 'track_duration_min', 'artist_genres_list', 'Year']

In [ ]:
df.head()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,artist_genres_list,Year
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55,[moombahton],2025
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07,"[country hip hop, southern hip hop]",2025
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,soundtrack,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55,[soundtrack],2025
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69,[moombahton],2025
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39,[dark r&b],2025

In [ ]:
list(df.columns)

['track_id',
 'track_name',
 'track_number',
 'track_popularity',
 'explicit',
 'artist_name',
 'artist_popularity',
 'artist_followers',
 'artist_genres',
 'album_id',
 'album_name',
 'album_release_date',
 'album_total_tracks',
 'album_type',
 'track_duration_min',
 'artist_genres_list',
 'Year']

In [ ]:
#Confirm cleaned dataset
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())
df.head()

Missing Values After Cleaning:
track_id              0
track_name            0
track_number          0
track_popularity      0
explicit              0
artist_name           0
artist_popularity     0
artist_followers      0
artist_genres         0
album_id              0
album_name            0
album_release_date    0
album_total_tracks    0
album_type            0
track_duration_min    0
artist_genres_list    0
Year                  0
dtype: int64

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,artist_genres_list,Year
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55,[moombahton],2025
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07,"[country hip hop, southern hip hop]",2025
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,soundtrack,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55,[soundtrack],2025
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69,[moombahton],2025
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39,[dark r&b],2025

In [ ]:
#VISUALIZATION#

In [ ]:
import plotly.express as px


fig = px.scatter(
    df.sample(5000),
    x='artist_popularity',
    y='track_popularity',
    color='artist_name',
    size='artist_followers',
    hover_data=['track_name', 'artist_name', 'artist_followers'],
    title="Artist Popularity vs Track Popularity (Bubble = Followers)",
    template='plotly_white'
)

fig.update_layout(
    dragmode='zoom',
    hovermode='closest',
    height=600,
    xaxis_title="Artist Popularity",
    yaxis_title="Track Popularity"
)

fig.update_traces(
    marker=dict(opacity=0.7, line=dict(width=0.5, color='DarkSlateGrey'))
)

fig.show()

In [ ]:
#POPULARITY OF GENRES
import pandas as pd
import plotly.express as px

# Drop rows without genres
df = df.dropna(subset=['artist_genres'])

# Split multiple genres
df_exploded = df.assign(
    artist_genres=df['artist_genres'].str.split(', ')
).explode('artist_genres')

# Count genres
genre_counts = (
    df_exploded['artist_genres']
    .value_counts()
    .reset_index()
)

# Rename properly
genre_counts.columns = ['genre', 'count']

# Select top 10
top_genres = genre_counts.head(10)

# Plot
fig = px.bar(
    top_genres,
    x='genre',
    y='count',
    title='Top 10 Most Popular Genres',
    labels={'genre': 'Genre', 'count': 'Count'},
    text='count',
    template='plotly_white'
)

fig.update_traces(marker=dict(opacity=0.85, line=dict(width=1)))
fig.update_layout(
    xaxis={'categoryorder': 'total descending'},
    height=600
)

fig.show()

In [ ]:
#Questionnaire#

🟦 Q1. How have global music streaming trends evolved over the years (2009–2025)?

In [ ]:

# Q1 : Average Track Popularity Over Time (2009–2025)

# 1) Create yearly summary statistics
ts_df = (
    df.dropna(subset=['Year'])
      .groupby('Year', as_index=False)
      .agg(
          avg_track_popularity=('track_popularity', 'mean'),
          median_track_popularity=('track_popularity', 'median'),
          count_tracks=('track_id', 'count')
      )
)

# 2) Restrict to 2009–2025
ts_df = ts_df[(ts_df['Year'] >= 2009) & (ts_df['Year'] <= 2025)]
ts_df = ts_df.sort_values('Year')

# 3) Main line chart
fig_q1 = px.line(
    ts_df,
    x='Year',
    y='avg_track_popularity',
    markers=True,
    title="Q1 — Average Track Popularity by Year (2009–2025)",
    labels={'avg_track_popularity': 'Avg Track Popularity'}
)

# 4) Add track count bar trace
fig_q1.add_bar(
    x=ts_df['Year'],
    y=ts_df['count_tracks'],
    name='Track Count',
    opacity=0.25,
    marker_line_width=0
)

# 5) Update layout
fig_q1.update_layout(
    template='plotly_white',
    height=500,
    yaxis_title="Avg Track Popularity",
    xaxis_title="Year"
)

# 6) Update ONLY the line traces (avoid messing up the bar)
fig_q1.update_traces(
    mode='lines+markers',
    selector=dict(type='scatter')
)

# 7) Show chart
fig_q1.show()

🟨 Q2. Which genres dominate the global music landscape, and how are genres distributed across tracks?

In [ ]:
# Q2: Genre -> Artist -> Track Sunburst
import pandas as pd
import plotly.express as px

# Load (if you want to re-load; skip if df already in memory)
# df = pd.read_csv("/mnt/data/spotify_data clean.csv")

# Ensure genre list column exists (created during preprocessing as artist_genres_list)
if 'artist_genres_list' not in df.columns and 'artist_genres' in df.columns:
    df['artist_genres_list'] = df['artist_genres'].fillna('Unknown').astype(str).str.split(r'[;,]\s*', regex=True)

# Explode into one row per (genre, artist, track)
df_sb = df.explode('artist_genres_list').copy()
df_sb['artist_genres_list'] = df_sb['artist_genres_list'].str.strip().replace('', 'Unknown').fillna('Unknown')

# Create a small count per track (1) used as value
df_sb['count'] = 1

# optional: keep top K genres for readability
top_genres = df_sb['artist_genres_list'].value_counts().head(15).index.tolist()
df_sb_small = df_sb[df_sb['artist_genres_list'].isin(top_genres)].copy()

fig_q3 = px.sunburst(
    df_sb_small,
    path=['artist_genres_list', 'artist_name', 'track_name'],
    values='count',
    maxdepth=3,
    title="Q3 — Genre → Artist → Track (Top genres)",
    template='plotly_white'
)
fig_q3.update_traces(textinfo='label+percent entry')
fig_q3.update_layout(height=700)
fig_q3.show()

🟧 Q3. How does track popularity change over time for the top artists or top tracks?

In [ ]:
# Q4: Multi-line time-series of avg track popularity for top artists with dropdown
import plotly.graph_objects as go
import numpy as np

# Make sure Year present
if 'Year' not in df.columns and 'album_release_date' in df.columns:
    df['album_release_date'] = pd.to_datetime(df['album_release_date'], errors='coerce')
    df['Year'] = df['album_release_date'].dt.year

artist_year = (
    df.dropna(subset=['Year'])
      .groupby(['artist_name','Year'], as_index=False)
      .agg(avg_track_popularity=('track_popularity','mean'), releases=('track_id','count'))
)

# Choose candidate artists (top by max followers)
artist_rank = df.groupby('artist_name', as_index=False).agg(max_followers=('artist_followers','max'))
artist_rank = artist_rank.sort_values('max_followers', ascending=False).head(20)
artist_candidates = artist_rank['artist_name'].tolist()

# Build figure: one trace per candidate artist (initially show top N)
N_init = 6
visible_init = [i < N_init for i in range(len(artist_candidates))]

fig_q4 = go.Figure()
for i, artist in enumerate(artist_candidates):
    d = artist_year[artist_year['artist_name'] == artist].sort_values('Year')
    fig_q4.add_trace(go.Scatter(
        x=d['Year'],
        y=d['avg_track_popularity'],
        mode='lines+markers',
        name=artist,
        visible=visible_init[i],
        hovertemplate='%{x}<br>%{y:.2f}<br>' + artist
    ))

# Dropdown buttons
buttons = []
options = [3, 6, 10, len(artist_candidates)]
for opt in options:
    vis = [i < opt for i in range(len(artist_candidates))]
    buttons.append(dict(label=f"Top {opt}", method="update", args=[{"visible": vis},
               {"title": f"Q4 — Avg Track Popularity Over Time (Top {opt} artists)"}]))

buttons.append(dict(label="Show all", method="update", args=[{"visible": [True]*len(artist_candidates)},
               {"title": "Q4 — Avg Track Popularity Over Time (All candidates)"}]))

fig_q4.update_layout(
    updatemenus=[dict(active=1, buttons=buttons, x=0.0, y=1.12)],
    title=f"Q4 — Avg Track Popularity Over Time (Top {N_init} artists shown)",
    xaxis_title="Year",
    yaxis_title="Avg Track Popularity",
    template='plotly_white',
    height=600
)
fig_q4.show()

Q4 🟦 Q4. What do the distributions of all available numeric features reveal about their spread, central tendency, and presence of outliers?

In [ ]:
# Q4: Boxplots and histograms for numeric features available in your dataset
import plotly.express as px

numeric_for_dist = [c for c in ['track_popularity','artist_popularity','artist_followers','track_duration_min','album_total_tracks'] if c in df.columns]
print("Numeric columns used for Q5:", numeric_for_dist)

if len(numeric_for_dist) == 0:
    print("No numeric columns found for distributions.")
else:
    # Sample for speed
    df_sample = df[numeric_for_dist].dropna().sample(min(5000, len(df)), random_state=1)

    # Combined box plot
    fig_q5_box = px.box(
        df_sample.melt(var_name='feature', value_name='value'),
        x='feature',
        y='value',
        points='outliers',
        title='Q5 — Box plots of numeric features',
        template='plotly_white'
    )
    fig_q5_box.update_layout(height=450)
    fig_q5_box.show()

Numeric columns used for Q5: ['track_popularity', 'artist_popularity', 'artist_followers', 'track_duration_min', 'album_total_tracks']

Q5 🟦 Q5. How strongly are the numeric features correlated with each other, and what key relationships can be identified from a correlation heatmap?

In [ ]:
# Q5: Correlation heatmap for numeric features
import plotly.graph_objects as go
corr_cols = [c for c in ['track_popularity','artist_popularity','artist_followers','track_duration_min','album_total_tracks'] if c in df.columns]

if len(corr_cols) < 2:
    print("Not enough numeric columns for correlation heatmap.")
else:
    corr = df[corr_cols].astype(float).corr().round(3)
    z = corr.values

    heatmap_q6 = go.Figure(data=go.Heatmap(
        z=z,
        x=corr.columns,
        y=corr.index,
        text=corr.values,
        texttemplate="%{text}",
        hoverongaps=False,
        colorscale='Viridis'
    ))

    heatmap_q6.update_layout(
        title="Q6 — Correlation Heatmap (numeric features)",
        template='plotly_white',
        height=500
    )
    heatmap_q6.show()